### PR TITLE
Fix hd60 backup and flashing

### PR DESCRIPTION
**Pull request by betacentauri**

### CODE REVIEW

**Comment by persianpros** [comment]
You should have push access right?

**Comment by betacentauri** [comment]
Yes, you're right. 
Do you know where I can see that I have push rights? Have looked before creating the PR and didn't see anything.

**Comment by persianpros** [comment]
I do check from https://github.com/OpenVisionE2/BackupSuite/settings/collaboration but I'm not sure you could see this page ...

**Comment by betacentauri** [comment]
No, can’t see that. 
But I found it. It’s hidden in the own user settings.

**Pull request merged**
